name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: 'Create release'

    permissions:
      contents: write

    uses: eliashaeussler/gha/.github/workflows/github-release.yaml@57463a2f9999f6212bdd43c29785fae78e01735b # 1.0.2
