name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: 'Create release'

    permissions:
      contents: write

    uses: eliashaeussler/gha/.github/workflows/github-release.yaml@637473b700af65935895aa936fab8c5319d3e765 # 1.1.12
